/* Rectangle.vala.c generated by valac 0.56.17, the Vala compiler
 * generated from Rectangle.vala, do not modify */

/* src/Rectangle.vala*/

#include <glib-object.h>
#include <glib.h>
#include <float.h>
#include <math.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_SHAPE (shape_get_type ())
#define SHAPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SHAPE, Shape))
#define SHAPE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SHAPE, ShapeClass))
#define IS_SHAPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SHAPE))
#define IS_SHAPE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SHAPE))
#define SHAPE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SHAPE, ShapeClass))

typedef struct _Shape Shape;
typedef struct _ShapeClass ShapeClass;
typedef struct _ShapePrivate ShapePrivate;

#define TYPE_RECTANGLE (rectangle_get_type ())
#define RECTANGLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RECTANGLE, Rectangle))
#define RECTANGLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RECTANGLE, RectangleClass))
#define IS_RECTANGLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RECTANGLE))
#define IS_RECTANGLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RECTANGLE))
#define RECTANGLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RECTANGLE, RectangleClass))

typedef struct _Rectangle Rectangle;
typedef struct _RectangleClass RectangleClass;
typedef struct _RectanglePrivate RectanglePrivate;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _Shape {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ShapePrivate * priv;
};

struct _ShapeClass {
	GTypeClass parent_class;
	void (*finalize) (Shape *self);
	gdouble (*get_area) (Shape* self);
	gdouble (*get_area_less_than_50000) (Shape* self);
	void (*move) (Shape* self, gint delta_x, gint delta_y);
};

struct _Rectangle {
	Shape parent_instance;
	RectanglePrivate * priv;
	gint width;
	gint height;
};

struct _RectangleClass {
	ShapeClass parent_class;
	void (*set_dimensions) (Rectangle* self, gint new_width, gint new_height);
};

static gpointer rectangle_parent_class = NULL;

VALA_EXTERN gpointer shape_ref (gpointer instance);
VALA_EXTERN void shape_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_shape (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags);
VALA_EXTERN void value_set_shape (GValue* value,
                      gpointer v_object);
VALA_EXTERN void value_take_shape (GValue* value,
                       gpointer v_object);
VALA_EXTERN gpointer value_get_shape (const GValue* value);
VALA_EXTERN GType shape_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Shape, shape_unref)
VALA_EXTERN GType rectangle_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Rectangle, shape_unref)
VALA_EXTERN void rectangle_set_dimensions (Rectangle* self,
                               gint new_width,
                               gint new_height);
VALA_EXTERN gdouble shape_get_area (Shape* self);
VALA_EXTERN gdouble shape_get_area_less_than_50000 (Shape* self);
VALA_EXTERN Rectangle* rectangle_new (gint width,
                          gint height);
VALA_EXTERN Rectangle* rectangle_construct (GType object_type,
                                gint width,
                                gint height);
VALA_EXTERN Shape* shape_construct (GType object_type);
static void rectangle_real_set_dimensions (Rectangle* self,
                                    gint new_width,
                                    gint new_height);
static gdouble rectangle_real_get_area (Shape* base);
static gdouble rectangle_real_get_area_less_than_50000 (Shape* base);
static void rectangle_finalize (Shape * obj);
static GType rectangle_get_type_once (void);

Rectangle*
rectangle_construct (GType object_type,
                     gint width,
                     gint height)
{
	Rectangle* self = NULL;
	_vala_return_val_if_fail ((width > 0) && (height > 0), "width > 0 && height > 0", NULL);
	self = (Rectangle*) shape_construct (object_type);
	self->width = width;
	self->height = height;
	_vala_warn_if_fail ((self->width == width) && (self->height == height), "this.width == width && this.height == height");
	return self;
}

Rectangle*
rectangle_new (gint width,
               gint height)
{
	return rectangle_construct (TYPE_RECTANGLE, width, height);
}

static void
rectangle_real_set_dimensions (Rectangle* self,
                               gint new_width,
                               gint new_height)
{
	_vala_return_if_fail ((new_width > 0) && (new_height > 0), "new_width > 0 && new_height > 0");
	self->width = new_width;
	self->height = new_height;
	_vala_warn_if_fail ((self->width == new_width) && (self->height == new_height), "this.width == new_width && this.height == new_height");
}

void
rectangle_set_dimensions (Rectangle* self,
                          gint new_width,
                          gint new_height)
{
	RectangleClass* _klass_;
	g_return_if_fail (self != NULL);
	_vala_return_if_fail ((new_width > 0) && (new_height > 0), "new_width > 0 && new_height > 0");
	_klass_ = RECTANGLE_GET_CLASS (self);
	if (_klass_->set_dimensions) {
		_klass_->set_dimensions (self, new_width, new_height);
		_vala_warn_if_fail ((self->width == new_width) && (self->height == new_height), "this.width == new_width && this.height == new_height");
	}
}

static gdouble
rectangle_real_get_area (Shape* base)
{
	Rectangle * self;
	gdouble result;
	self = (Rectangle*) base;
	result = (gdouble) (self->width * self->height);
	return result;
}

static gdouble
rectangle_real_get_area_less_than_50000 (Shape* base)
{
	Rectangle * self;
	gdouble result;
	self = (Rectangle*) base;
	result = (gdouble) (self->width * self->height);
	_vala_warn_if_fail ((result >= 0.0) && (result <= 50000.0), "result >= 0.0 && result <= 50000.0");
	return result;
}

static void
rectangle_class_init (RectangleClass * klass,
                      gpointer klass_data)
{
	rectangle_parent_class = g_type_class_peek_parent (klass);
	((ShapeClass *) klass)->finalize = rectangle_finalize;
	((RectangleClass *) klass)->set_dimensions = (void (*) (Rectangle*, gint, gint)) rectangle_real_set_dimensions;
	((ShapeClass *) klass)->get_area = (gdouble (*) (Shape*)) rectangle_real_get_area;
	((ShapeClass *) klass)->get_area_less_than_50000 = (gdouble (*) (Shape*)) rectangle_real_get_area_less_than_50000;
}

static void
rectangle_instance_init (Rectangle * self,
                         gpointer klass)
{
}

static void
rectangle_finalize (Shape * obj)
{
	Rectangle * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_RECTANGLE, Rectangle);
	SHAPE_CLASS (rectangle_parent_class)->finalize (obj);
}

static GType
rectangle_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (RectangleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rectangle_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Rectangle), 0, (GInstanceInitFunc) rectangle_instance_init, NULL };
	GType rectangle_type_id;
	rectangle_type_id = g_type_register_static (TYPE_SHAPE, "Rectangle", &g_define_type_info, 0);
	return rectangle_type_id;
}

GType
rectangle_get_type (void)
{
	static volatile gsize rectangle_type_id__once = 0;
	if (g_once_init_enter (&rectangle_type_id__once)) {
		GType rectangle_type_id;
		rectangle_type_id = rectangle_get_type_once ();
		g_once_init_leave (&rectangle_type_id__once, rectangle_type_id);
	}
	return rectangle_type_id__once;
}

