/* RectangleDerived.vala.c generated by valac 0.56.17, the Vala compiler
 * generated from RectangleDerived.vala, do not modify */

/* src/RectangleDerived.vala*/

#include <glib-object.h>
#include <glib.h>
#include <float.h>
#include <math.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_SHAPE (shape_get_type ())
#define SHAPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SHAPE, Shape))
#define SHAPE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SHAPE, ShapeClass))
#define IS_SHAPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SHAPE))
#define IS_SHAPE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SHAPE))
#define SHAPE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SHAPE, ShapeClass))

typedef struct _Shape Shape;
typedef struct _ShapeClass ShapeClass;
typedef struct _ShapePrivate ShapePrivate;

#define TYPE_RECTANGLE (rectangle_get_type ())
#define RECTANGLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RECTANGLE, Rectangle))
#define RECTANGLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RECTANGLE, RectangleClass))
#define IS_RECTANGLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RECTANGLE))
#define IS_RECTANGLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RECTANGLE))
#define RECTANGLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RECTANGLE, RectangleClass))

typedef struct _Rectangle Rectangle;
typedef struct _RectangleClass RectangleClass;
typedef struct _RectanglePrivate RectanglePrivate;

#define TYPE_RECTANGLE_DERIVED (rectangle_derived_get_type ())
#define RECTANGLE_DERIVED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RECTANGLE_DERIVED, RectangleDerived))
#define RECTANGLE_DERIVED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RECTANGLE_DERIVED, RectangleDerivedClass))
#define IS_RECTANGLE_DERIVED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RECTANGLE_DERIVED))
#define IS_RECTANGLE_DERIVED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RECTANGLE_DERIVED))
#define RECTANGLE_DERIVED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RECTANGLE_DERIVED, RectangleDerivedClass))

typedef struct _RectangleDerived RectangleDerived;
typedef struct _RectangleDerivedClass RectangleDerivedClass;
typedef struct _RectangleDerivedPrivate RectangleDerivedPrivate;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _Shape {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ShapePrivate * priv;
};

struct _ShapeClass {
	GTypeClass parent_class;
	void (*finalize) (Shape *self);
	gdouble (*get_area) (Shape* self);
	gdouble (*get_area_less_than_50000) (Shape* self);
	void (*move) (Shape* self, gint delta_x, gint delta_y);
};

struct _Rectangle {
	Shape parent_instance;
	RectanglePrivate * priv;
	gint width;
	gint height;
};

struct _RectangleClass {
	ShapeClass parent_class;
	void (*set_dimensions) (Rectangle* self, gint new_width, gint new_height);
};

struct _RectangleDerived {
	Rectangle parent_instance;
	RectangleDerivedPrivate * priv;
};

struct _RectangleDerivedClass {
	RectangleClass parent_class;
};

static gpointer rectangle_derived_parent_class = NULL;

VALA_EXTERN gpointer shape_ref (gpointer instance);
VALA_EXTERN void shape_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_shape (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags);
VALA_EXTERN void value_set_shape (GValue* value,
                      gpointer v_object);
VALA_EXTERN void value_take_shape (GValue* value,
                       gpointer v_object);
VALA_EXTERN gpointer value_get_shape (const GValue* value);
VALA_EXTERN GType shape_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Shape, shape_unref)
VALA_EXTERN GType rectangle_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Rectangle, shape_unref)
VALA_EXTERN GType rectangle_derived_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (RectangleDerived, shape_unref)
VALA_EXTERN void rectangle_set_dimensions (Rectangle* self,
                               gint new_width,
                               gint new_height);
VALA_EXTERN void shape_move (Shape* self,
                 gint delta_x,
                 gint delta_y);
VALA_EXTERN RectangleDerived* rectangle_derived_new (gint width,
                                         gint height);
VALA_EXTERN RectangleDerived* rectangle_derived_construct (GType object_type,
                                               gint width,
                                               gint height);
VALA_EXTERN Rectangle* rectangle_new (gint width,
                          gint height);
VALA_EXTERN Rectangle* rectangle_construct (GType object_type,
                                gint width,
                                gint height);
static void rectangle_derived_real_set_dimensions (Rectangle* base,
                                            gint new_width,
                                            gint new_height);
static void rectangle_derived_real_move (Shape* base,
                                  gint delta_x,
                                  gint delta_y);
static GType rectangle_derived_get_type_once (void);

RectangleDerived*
rectangle_derived_construct (GType object_type,
                             gint width,
                             gint height)
{
	RectangleDerived* self = NULL;
	_vala_return_val_if_fail ((width > 0) && (height > 0), "width > 0 && height > 0", NULL);
	self = (RectangleDerived*) rectangle_construct (object_type, width, height);
	_vala_warn_if_fail ((((Rectangle*) self)->width == width) && (((Rectangle*) self)->height == height), "this.width == width && this.height == height");
	return self;
}

RectangleDerived*
rectangle_derived_new (gint width,
                       gint height)
{
	return rectangle_derived_construct (TYPE_RECTANGLE_DERIVED, width, height);
}

static void
rectangle_derived_real_set_dimensions (Rectangle* base,
                                       gint new_width,
                                       gint new_height)
{
	RectangleDerived * self;
	self = (RectangleDerived*) base;
	_vala_return_if_fail ((((new_width > 0) && (new_height > 0)) && (new_width <= 100)) && (new_height <= 100), "new_width > 0 && new_height > 0 && new_width <= 100 && new_height <= 100");
	RECTANGLE_CLASS (rectangle_derived_parent_class)->set_dimensions (G_TYPE_CHECK_INSTANCE_CAST (self, TYPE_RECTANGLE, Rectangle), new_width, new_height);
	_vala_warn_if_fail ((((Rectangle*) self)->width == new_width) && (((Rectangle*) self)->height == new_height), "this.width == new_width && this.height == new_height");
}

static void
rectangle_derived_real_move (Shape* base,
                             gint delta_x,
                             gint delta_y)
{
	RectangleDerived * self;
	self = (RectangleDerived*) base;
	_vala_return_if_fail ((((delta_x >= -10) && (delta_x <= 10)) && (delta_y >= -10)) && (delta_y <= 10), "delta_x >= -10 && delta_x <= 10 && delta_y >= -10 && delta_y <= 10");
	SHAPE_CLASS (rectangle_derived_parent_class)->move ((Shape*) G_TYPE_CHECK_INSTANCE_CAST (self, TYPE_RECTANGLE, Rectangle), delta_x, delta_y);
}

static void
rectangle_derived_class_init (RectangleDerivedClass * klass,
                              gpointer klass_data)
{
	rectangle_derived_parent_class = g_type_class_peek_parent (klass);
	((RectangleClass *) klass)->set_dimensions = (void (*) (Rectangle*, gint, gint)) rectangle_derived_real_set_dimensions;
	((ShapeClass *) klass)->move = (void (*) (Shape*, gint, gint)) rectangle_derived_real_move;
}

static void
rectangle_derived_instance_init (RectangleDerived * self,
                                 gpointer klass)
{
}

static GType
rectangle_derived_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (RectangleDerivedClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rectangle_derived_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RectangleDerived), 0, (GInstanceInitFunc) rectangle_derived_instance_init, NULL };
	GType rectangle_derived_type_id;
	rectangle_derived_type_id = g_type_register_static (TYPE_RECTANGLE, "RectangleDerived", &g_define_type_info, 0);
	return rectangle_derived_type_id;
}

GType
rectangle_derived_get_type (void)
{
	static volatile gsize rectangle_derived_type_id__once = 0;
	if (g_once_init_enter (&rectangle_derived_type_id__once)) {
		GType rectangle_derived_type_id;
		rectangle_derived_type_id = rectangle_derived_get_type_once ();
		g_once_init_leave (&rectangle_derived_type_id__once, rectangle_derived_type_id);
	}
	return rectangle_derived_type_id__once;
}

